server:
  port: ":8082"

env: "staging"

log:
  level: "debug"
  format: "json"
  request: true
  response: true
  request_debug: true

service:
  name: "oms_service"

migration:
  flag: true

omsService:
  mongoURI: ""